# Generated by Django 2.0.6 on 2020-01-22 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roledetails',
            name='is_active',
            field=models.NullBooleanField(default=0),
        ),
    ]
