# Generated by Django 2.0.6 on 2020-02-05 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0002_auto_20200122_1625'),
        ('admin_app', '0002_auto_20200122_1614'),
    ]

    operations = [
    ]
