# Generated by Django 2.0.6 on 2020-01-22 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('front_app', '0002_roledetails'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roledetails',
            name='role_id',
        ),
        migrations.DeleteModel(
            name='RoleDetails',
        ),
        migrations.DeleteModel(
            name='UserRole',
        ),
    ]
